[package]
name = "rust-csv-crud"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.1"
serde = "1.0.162"
chrono = "0.4.24"
serde-error = "0.1.2"